temperature: 0.1
normalize: true
bs: 128
lmda1: 0.001
lmda2: 0.1
epochs: 200
p_iter: 320
s_epoch: 5
save_buffer: true

data:
  data_dir : "./data"
  dataset : "cifar10"
  data_ratio : 1.0

sgld:
  iter: 10
  lr: 0.05
  min_std: 0.01
  max_std: 0.05
  threshold: 3.0
  tau: 1.0

buffer:
  CD_ratio: 1.0
  size: 50000
  rho: 0.2
  bs: 256

optim:
  optimizer: "adam"
  init_lr: 0.0002
  lr_schedule: "const"

net:
  encoder: "resnet18"
  use_bn: false
  use_sn: false
  use_wn: false
  act: "lrelu"
  proj_dim: 128
  nc: 3

t:
  crop_scale:
    min: 0.08
    max: 1.0
  flip_p : 0.5
  jitter:
    b: 0.8
    c: 0.8
    s: 0.8
    h: 0.2
  jitter_p : 0.8
  gray_p : 0.2
  blur_scale : 0.1
  noise_std : 0.03